name: JSON PR Validator
on:
  pull_request:
    branches:
    - Goats-Mod-Compilation
    types: [opened, edited, synchronize]
jobs:
  style-json:
    name: JSON style check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 10
      - name: JSON style check
        run: make style-json
      - name: Display Corrections
        if: failure()
        run: git diff
