name: C/C++ CI

on: [push]
    [pull_request]
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: nicledomaS/cmake_build_action@v1
      with:
        run_tests: ON
        unit_test_build: -Dtest=ON
